ident/api/urls.py
from django.conf.urls import include, url

#from ident.api.handlers import *
from ident.dent.views import JsonLastDentDetailView, APIDentCreateView
from ident.user.views import JsonUserView, list_users_as_json

#auth = OAuthAuthentication(realm='http://id3nt.i2p')
#root_handler = Resource(RootHandler)
#dents_handler = Resource(DentsHandler, authentication=auth)
#dent_handler = Resource(DentHandler)
#users_handler = Resource(UsersHandler)
#user_handler = Resource(UserHandler)

urlpatterns = [
    # API v1
    url(r'^1/u/id_(?P<pk>\d+)/$', JsonUserView.as_view()),
    url(r'^1/u/(?P<username>[\w-]+)/$', JsonUserView.as_view()),
    url(r'^1/u/$', list_users_as_json), #user list
    url(r'^1/u/(?P<username>[\w-]+)/d/last/$', JsonLastDentDetailView.as_view()),
    url(r'^1/d/create/$', APIDentCreateView.as_view()),

    # API v2.0
#    url(r'^2.0/u/id_(?P<pk>\d+)/', user_handler),
#    url(r'^2.0/u/(?P<username>[\w-]+)/', user_handler),
#    url(r'^2.0/u/', users_handler),
#    url(r'^2.0/d/(?P<pk>\d+)/', dent_handler),
#    url(r'^2.0/d/', dents_handler),
#    url(r'^2.0/', root_handler),

    # Twitter-like APIs
    url(r'^twitter/', include('ident.api.twitter.urls')),
]

# OAuth
#urlpatterns += [
#    url(r'^oauth/request_token/$', oauth_request_token, name='oauth_request_token'),
#    url(r'^oauth/authorize/$', oauth_user_auth, name='oauth_user_auth'),
#    url(r'^oauth/access_token/$', oauth_access_token, name='oauth_access_token'),
#]

ident/dent/urls.py
from django.conf.urls import url

from ident.dent.models import Dent
from ident.dent.views import dent_delete, dent_vote,\
                       privatedent_delete,\
                       DentDetailView, DentCreateView, DentEditView,\
                       PrivateDentDetailView, PrivateDentCreateView, PrivateDentEditView
from ident.user.views import user_follow

urlpatterns = [
    # create new dent
    url(r'^new/?$', DentCreateView.as_view(), name='dent_create_view'),
    url(r'^(?P<pk>\d+)/?$', DentDetailView.as_view(), name='dent_detail_view'),
    # reply to a dent
    url(r'^(?P<replyto_id>\d+)/reply/?$', DentCreateView.as_view(),
        name='dent_reply_view'),
    url(r'^(?P<dent_id>\d+)/edit/?$', DentEditView.as_view(),
        name='dent_edit'),
    url(r'^(?P<dent_id>\d+)/delete/?$', dent_delete,
        name='dent_delete'),
    url(r'^(?P<dent_id>\d+)/stalk/?$', user_follow),
    url(r'^(?P<dent_id>\d+)/vote(/up)?/?$', dent_vote, {'down': False},
        name='dent_vote_up'),
    url(r'^(?P<dent_id>\d+)/vote/down/?$', dent_vote, {'down': True},
        name='dent_vote_down'),
    # private dents
    url(r'^p/new/?$', PrivateDentCreateView.as_view(), name='privatedent_create_view'),
    url(r'^p/(?P<pk>\d+)/?$', PrivateDentDetailView.as_view(), name='privatedent_detail_view'),
    url(r'^p/(?P<pdent_id>\d+)/edit/?$', PrivateDentEditView.as_view(),
        name='privatedent_edit'),
    url(r'^p/(?P<pdent_id>\d+)/delete/?$', privatedent_delete,
        name='privatedent_delete'),
]

ident/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from reputation.registry import reputation_registry

from ident.dent.feed import LatestEntriesFeed
from ident.dent.models import DentingReputationHandler, VotingReputationHandler
from ident.dent.views import DentListView, FeedbackPrivateDentCreateView
from ident.user.views import UserProfileView, current_user_home, user_register
from ident.views import IdentTemplateView, StatisticsView, MessageView, index_handler

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

reputation_registry.register(DentingReputationHandler)
reputation_registry.register(VotingReputationHandler)

urlpatterns = [
    # Homepage view of recent dents:
    url(r'^/?$', index_handler,
        name="index"),
    url(r'^all(/by_(?P<sort_by>[-\w]+))?\/?$', DentListView.as_view(),
        name="homepage"),
    url(r'^u/', include('ident.user.urls')),
    url(r'^members/', include('ident.user.member_urls')),
    url(r'^api/', include('ident.api.urls')),
    url(r'^accounts/logged_in/', current_user_home),
    url(r'^accounts/password\/?$', UserProfileView.as_view()),
    # Don't use registration backend, we don't want email confirmation.
    #url(r'^accounts/', include('registration.backends.default.urls')),
    # For all the rest use the defaults
    url(r'^accounts/register/$', user_register),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^search/', include('ident.search.urls')),
    url(r'^hashtags/', include('hashtags.urls')),
    url(r'^dent/', include('ident.dent.urls')),
    url(r'^private/', include('ident.dent.private_urls')),
    url(r'^feed$', LatestEntriesFeed()),
    url(r'^about/?$', IdentTemplateView.as_view(template_name='about.html'),
        name='about_page'),
    url(r'^usage/?$', IdentTemplateView.as_view(template_name='usage.html'),
        name='api_usage'),
    url(r'^donate/?$', IdentTemplateView.as_view(template_name='donate.html'),
        name='donate_page'),
    url(r'^stats/?$', StatisticsView.as_view(),
        name='statistics_main'),
    url(r'^hello-spider/?$', DentListView.as_view(template_name= 'geti2p.html'),
                   {'sort_by':'vote'}),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    #url(r'^admin/(.*)', admin.site.root),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^msg$', MessageView.as_view(), name='generic_message'),
    url(r'^messages/', include('messages_extends.urls')),
    url(r'^feedback/?$', login_required(FeedbackPrivateDentCreateView.as_view()),
        name='feedback_page'),
]

if settings.DEBUG:
    urlpatterns += [
        # Make sure you serve the /media files through your web server
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': '/home/str4d/dev/git/ident/ident/media/'}),
    ]

ident/user/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from ident.dent.feed import LatestUserEntriesFeed,LatestUserStalkingFeed
from ident.dent.views import UserDentListView
from ident.user import views

# user RSS feed
urlpatterns = [
    url(r'^((?P<username>[^/]+))/feed$', LatestUserEntriesFeed(),
        name='latest_user_feed'),
    url(r'^((?P<username>[^/]+))/stalking/feed$', LatestUserStalkingFeed(),
        name='latest_stalking_feed')
]
# handle URL: /u/...
urlpatterns += [
    url(r'^/?$', views.list_users), #List of all users
    url(r'^(?P<username>.*[^/])/profile/?$', views.UserProfileView.as_view(),
        name='profilepage'),
    url(r'^(?P<username>.*[^/])/dashboard/?$', views.UserDetailView.as_view(),
        name='user_dashboard'),
    # user profile change user email is now integrated in regular
    # profile edit, so redirect there
    url(r'^(?P<username>.*[^/])/profile/change_email/?$', RedirectView.as_view(
            url='/u/%(username)s/profile/edit/')),
    url(r'^(?P<username>.*[^/])/profile/edit/?$', views.edit_profile,
        name='edit_profile'), #edit user profile
    url(r'^(?P<username>.*[^/])/delete/?$', views.user_delete,
        name='user_delete'), #delete user!
    url(r'^(?P<username>.*[^/])/stalk/?$', views.user_follow,
        name='user_follow'), #follow user
    url(r'^(?P<username>.*[^/])/unstalk/?$', views.user_unfollow,
        name='user_unfollow'), #follow user
    url(r'^(?P<username>[^/]+)/stalking(/by_(?P<sort_by>[-\w]+))?/?$',
        UserDentListView.as_view(), {'stalkovision': True},
        name='stalk-o-vision'), #stalkovision view
    url(r'^(?P<username>[^/]+)(/by_(?P<sort_by>[-\w]+))?/?$',
        UserDentListView.as_view(),
        name='user_home'), #display user homepage
]

ident/dent/models.py
from __future__ import division
import datetime
import re

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import force_escape, striptags, urlizetrunc,\
    linebreaks, truncatewords
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from hashtags.signals import (hashtagged_model_was_saved,
                              hashtagged_model_was_deleted,
                              parse_fields_looking_for_hashtags,
                              handle_removal_of_hashtagged_model)
from hashtags.templatetags.hashtags_tags import urlize_hashtags
from reputation.handlers import BaseReputationHandler

from ident.dent.fields import LanguageField

hashtagged_model_was_saved.connect(parse_fields_looking_for_hashtags)
hashtagged_model_was_deleted.connect(handle_removal_of_hashtagged_model)

class AbstractDent(models.Model):
    text = models.CharField(max_length=1024)
    poster = models.ForeignKey(User, blank=True)
    time = models.DateTimeField(auto_now_add=True)

    #at_user_re = re.compile('^(?P<prefix>.*\s)?(?P<atname>@[\w\-]+)(?P<appendix>.*)$')

    # words longer than 25 alphanumerics, but only if not preceeded by
    # :// (url scheme)
    truncate_re = re.compile("""
    (^|\s)                         # either string start or after space
    (?P<longword>([^"\s#][^"\s]{12})      # 13 nonspaces, not containing ", not starting in #
                                   # (used for abbreviation), followed by
     ((?<!://)\S){13,}             # >=13 more nonspaces
    )
    \\b                            #end of alphanumeric word
    """, re.VERBOSE)
    atUser_re = re.compile('(^|\s)@(?P<username>[.+\w-]+[@.+\w-]*)\\b')

    def __unicode__(self):
        return u"%d (%s): %s" % (self.id,
                             self.poster.username,
                             truncatewords(self.text, 5))

    def get_follow_url(self):
        return self.get_absolute_url() + '/follow'

    def text_as_html(self):
        """Return the body of the dent as properly formatted html.

        This is done when viewed instead of by the form, so that dents
        can be edited by the user."""
        # escape HTML tags instead of stripping them
        text = force_escape(self.text)
        #text = striptags(self.text)
        if self.poster.has_perm('ident.new_user_restrictions_lifted'):
            text = urlizetrunc(text, 60)
        #disabled by dr|z3d: text = linebreaks(text)

        #find overly long words and truncate them
        text = Dent.truncate_re.sub('\\1<span class="truncated" title="\\g<longword>">[\\3&hellip;]</span>', text)

        # find @User and convert them to links
        text = Dent.atUser_re.sub('\\1<a href="/u/\\g<username>">@\\g<username></a> ', text)
        # find hashtags and convert them to links
        text = urlize_hashtags(text)
        return mark_safe(text)

    class Meta:
        abstract = True
        ordering = ('-time', )
        get_latest_by = 'time'


class Dent(AbstractDent):
    # The dent this dent is a reply to
    in_reply_to = models.ForeignKey('self', null=True, blank=True,
                                    related_name='replies', default=None)

    source = models.CharField(max_length=140, default='Web')

    # The language of the dent
    language = LanguageField(blank=True, default='en')

    # The votes for this dent
    votes = models.ManyToManyField(User, blank=True, through='Vote',
                                   related_name='votes')
    # this one is automatically updated when a vote occurs and reflects the
    # aggregated + and - votes.
    vote_sum = models.IntegerField(default=0, blank=False, editable=False)
    # this one is automatically updated when a vote occurs and reflects the
    # calculated popularity of the dent.
    popularity = models.DecimalField(default=0, blank=False, editable=False, max_digits=6, decimal_places=5)
    # this stores the calculated popularity of the dent damped by its age
    # and is updated when a vote occurs and by cron job
    damped_popularity = models.DecimalField(default=0, blank=False, editable=False, max_digits=6, decimal_places=5)

    # the last time the dent was featured as a dent-du-jour.
    last_featured = models.DateTimeField(default=datetime.datetime.utcfromtimestamp(0), blank=False, editable=False)
    # the number of times the dent has been featured as a dent-du-jour;
    # this is auto-incremented when a new dent-du-jour is chosen.
    times_featured = models.IntegerField(default=0, blank=False, editable=False)

    @models.permalink
    def get_absolute_url(self):
        return ('dent_detail_view', () ,{'pk': self.id})

    def get_reply_url(self):
        return self.get_absolute_url() + '/reply'

    def get_thread_list(self):
        """Returns direct replies to this thread in a list"""
        thread= [self]
        dent= self
        while dent.in_reply_to:
            thread.append(dent.in_reply_to)
            dent = dent.in_reply_to
        # Dents should be displayed newest-first
        #thread.reverse()
        return thread

    def calculate_popularity(self):
        """Calculate and return a dent's popularity.

        Invoked when a dent has been voted on. If the site becomes more
        popular, this should be moved to a cron job, and the dent should
        just be flagged for update when it is voted on."""
        # Calculate some parameters
        total_votes = Vote.objects.count() or 1
        total_dents = Dent.objects.count() or 1
        avg_num_votes = total_votes / total_dents
        total_vote_sum = Dent.objects.aggregate(models.Sum('vote_sum')).get('vote_sum__sum', 0)
        avg_vote = total_vote_sum / total_votes
        num_votes = self.vote_set.count()

        # Calculate the popularity with an adaptive Bayesian average
        popularity = (avg_num_votes * avg_vote) + self.vote_sum
        popularity = popularity / (avg_num_votes + num_votes)

        return popularity

    def calculate_damped_popularity(self):
        """Calculate and return the damped popularity of a dent.

        This is kept separate from the absolute popularity so that the more
        expensive/db-heavy popularity calculation only needs to be performed
        when a dent is voted on, while the lower-overhead age damping is
        performed daily for all dents.

        This value is stored rather than calculated on-the-fly because sorting
        the dents is much faster in the database than in Python (which would
        require fetching all Dents into memory and sorting them for every page
        request, regardless of how many would eventually be displayed)."""
        # Calculate the damped popularity
        if self.popularity > 0:
            age = datetime.datetime.now() - self.time
            age = age.days or 1
            damped_popularity = self.popularity / (age**0.02)
        else:
            damped_popularity = self.popularity

        return damped_popularity

    def update_popularity(self):
        """Update a dent's popularity and save it."""
        # Get the popularity of this dent
        popularity = self.calculate_popularity()

        # Save the popularity if it has changed
        if self.popularity != popularity:
            self.popularity = popularity
            self.save()

    def update_damped_popularity(self):
        """Update the damped popularity of a dent and save it.

        Invoked daily by a cron job."""
        # Get the damped popularity of this dent
        damped_popularity = self.calculate_damped_popularity()

        # Save the damped popularity if it has changed
        if self.damped_popularity != damped_popularity:
            self.damped_popularity = damped_popularity
            self.save()


# Capture Dent creation/modification signal and update user's karma
@receiver(models.signals.post_save, sender=Dent)
def dent_created_updated (sender, *args, **kwargs):
    dent = kwargs.get('instance')
    if kwargs.get('created'):
        dent.popularity = dent.calculate_popularity()
        dent.damped_popularity = dent.calculate_damped_popularity()
        dent.save()
        if not dent.poster.has_perm('ident.new_user_restrictions_lifted'):
            dent.poster.profile.check_new_user_restrictions()
    hashtagged_model_was_saved.send(sender=sender, instance=dent,
        hashtagged_field_list=['text'])
models.signals.post_save.connect(dent_created_updated, sender=Dent)

@receiver(models.signals.pre_delete, sender=Dent)
def dent_deleted(sender, instance, **kwargs):
    hashtagged_model_was_deleted.send(sender=sender, instance=instance)
models.signals.pre_delete.connect(dent_deleted, sender=Dent)


class DentingReputationHandler(BaseReputationHandler):
    model = Dent
    CREATE_VALUE = 1

    def check_conditions(self, instance):
        return True

    def remove_on_delete(self, instance):
        return True

    def get_target_object(self, instance):
        return instance

    def get_target_user(self, instance):
        return instance.poster

    def get_originating_user(self, instance):
        return instance.poster

    def get_value(self, instance):
        return self.CREATE_VALUE


class PrivateDent(AbstractDent):
    """Dents that target only a user or a group"""
    # receiver of the Private Message
    rec_user = models.ForeignKey(User, blank=False, null=False, related_name="received_privatedent_set", verbose_name="Recipient")

    @models.permalink
    def get_absolute_url(self):
        return ('privatedent_detail_view', () ,{'pk': self.id})

    def get_thread_list(self):
        """Returns private dents that give context to this one in a list"""
        thread = PrivateDent.objects.filter(

ident/templates/user/change_email.html
{% extends "user/user.html" %}
{% load i18n %}
{% block breadcrumb %}{{ block.super }}<a href="">{% trans "Profile" %}</a>{% endblock %}
{% block content %}
<h1>{% blocktrans with name=u.username %}User profile for {{ name }}{% endblocktrans %}</h1>

<form action="{{request.META.DOCUMENT_URI}}" method="post" enctype="multipart/form-data">
<table>
{{form.as_table}}
<tr>
<td></td><td><input type="submit" value="{% trans "Submit changes" %}"/></td></tr>
</table>
{% csrf_token %}
</form>
{% endblock content %}

ident/templates/user/dashboard.html
{% extends "user/user.html" %}

{% block content %}
Content to be inserted here... Examples:<br/><br/>

* n mentions of you since last login (m total)<br/>
* n new dents since last login. See in chronological order here...<br/>
* n dents containing hashtags you stalk since last login. See in chronological order here...<br/>

{% endblock content %}

ident/templates/user/edit_profile.html
{% extends "user/user.html" %}
{% load i18n %}
{%block heading%}<h1>{% blocktrans with name=u.username %}User profile for {{ name }}{% endblocktrans %}</h1>{%endblock%}
{% block content %}
<form action="{{request.META.DOCUMENT_URI}}" method="post" enctype="multipart/form-data">
<table class="profileedit">
{{form_email.as_table}}
{{form.as_table}}
{{form_site_setting}}
<tr>
<td></td><td><input type="submit" value="{% trans "Submit changes" %}"/></td></tr>
</table>
{% csrf_token %}
</form>
{% endblock content %}

ident/templates/user/profile.html
{% extends "user/user.html" %}
{% load i18n %}

{% block heading %}<h1>{% blocktrans with name=u.username|capfirst %}{{ name }}'s profile{% endblocktrans %} <a href="{% url "edit_profile" u.username %}"><input type="submit" value="{% trans "Edit" %}"/></a></h1>{% endblock %}
{% block content %}
<div class="identification">
<table class="profile">{% with u.profile as profile %}
<tr><td>{% trans "Avatard:" %}</td>
  <td>{% if profile.avatar %}
     <img src="{{MEDIA_URL}}{{profile.avatar}}"/>
     {% else %}{% url "edit_profile" u.username as edit_url %}{% blocktrans %}None yet, you are still a bum! Hurry, and <a href="{{ edit_url }}">upload one</a>.{% endblocktrans %}{%endif%}
  </td>
</tr>
<tr><td>{% trans "Joined:" %}</td><td>{{u.date_joined|date:"d M Y"}}{% if u.is_superuser %} and is a superuser{% endif%}</td></tr>
<tr><td>{% trans "Last login:" %}</td><td>{% blocktrans with duration=u.last_login|timesince %}{{duration}} ago{% endblocktrans %}</td></tr>
<tr><td>{% trans "E-mail:" %}</td><td> {{ u.email }} {%if profile.email_is_public %}{% trans "(is public)" %} {%endif%}</td></tr>
<tr><td>I2Pbote:</td><td>{%if profile.i2pbote %}{{ profile.i2pbote|slice:":30" }}&hellip;{%else%}{% blocktrans with url='http://i2pbote.i2p' %}None, why don't you <a href="{{url}}">get one</a>?{% endblocktrans %}{%endif%}</td></tr>
<tr><td>I2PMessenger:</td><td>{%if profile.i2pmessenger %}{{ profile.i2pmessenger|slice:":30" }}&hellip;{%else%}{% blocktrans with url='http://echelon.i2p/qti2pmessenger/' %}None, why don't you <a href="{{url}}">get one</a>?{% endblocktrans %}{%endif%}</td></tr>
<tr><td>Nightweb:</td><td>{%if profile.nightweb %}<a href="http://nightweb.net/#type=user&userhash={{profile.nightweb}}">{{ profile.nightweb|slice:":30" }}&hellip;</a>{%else%}{% blocktrans with url='https://nightweb.net/' %}None, why don't you <a href="{{url}}">get one</a>?{% endblocktrans %}{%endif%}</td></tr>
<tr class="off"><td>www:</td><td>{{ profile.homepage }}</td></tr>
<tr><td>{% trans "Description:" %}</td><td>{{ profile.description }}</td></tr>
<tr><td>{% trans "Language:" %}</td><td>{% if u.sitesettings.language %}{{ u.sitesettings.language }}{% else %}en{% endif %}</td></tr>
<tr><td>{% trans "Index page:" %}</td><td><a href="{% url "index" %}">{{ u.sitesettings.get_index_page_display }}</a></td></tr>
<tr><td>{% trans "Session timeout:" %}</td><td>{{ u.sitesettings.session_timeout }}</td></tr>
<tr><td>{% trans "Theme:" %}</td><td>{% if u.sitesettings.theme %}{{ u.sitesettings.theme }}{% else %}burgundy{% endif %}</td></tr>
<tr><td>{% trans "User CSS:" %}</td><td> {{ u.sitesettings.user_css }}</td></tr>
<tr><td>{% trans "Password:" %}</td><td>*** <a href="{% url "password_change" %}"><input type="submit" value="{% trans "Change Password" %}"/></a></td></tr>
<tr><td colspan="2"><a href="{% url "user_delete" u.username %}"><input type="submit" value="{% blocktrans %}Delete '{{u}}'{% endblocktrans %}"/></a> <b>{% trans "WARNING, there is no undelete!" %}</td></tr>
</table>{%endwith%}
<div>
{% endblock content %}

ident/templates/user/user_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block heading %}<h1>{% trans "Confirm user nukage!" %}</h1>{% endblock %}
{% block content %}
<h4><span class="greenText">{% blocktrans %}You are about to smoke this user, the associated profile and <b>all</b> their precious dents. Hit "Delete!" <i>only</i> if you are sure you REALLY want to do this, there is NO UNDO! Or, you can haz account deactivation, disabling login while retaining the user's profile and dents.{% endblocktrans %}</span></h4>

{% with profile=object.profile %}
<article class="greenText"><h3>User #{{object.id}}: {{object}} {% if object.first_name or object.last_name%}({{object.first_name}} {{object.last_name}}){%endif%} signed up on {{object.date_joined}} ({{object.date_joined|timesince}} ago). The user has posted a total of {{profile.dent_count}} dent{{profile.dent_count|pluralize}}.</h3>
<p>{% trans "The user's last 3 dents were:" %}</p>{% for dent in object.dent_set.all|slice:":3"%}{% include 'inc/dent.html' with dent=dent %}{%endfor%}</article>
{%endwith%}
<form action="{{request.META.PATH_INFO}}" method="post">
  <input type="submit" value="{% blocktrans %}DEACTIVATE '{{object}}' but KEEP related dents/votes!{% endblocktrans %}"/>
  {% csrf_token %}{% csrf_token %}
</form>
<br/>
<form action="{{request.META.PATH_INFO}}" method="post">
  <input type="hidden" name="realdelete" value="1"/>
  <input type="submit" value="{% blocktrans %}DELETE '{{object}}' and ALL related dents/votes !!!{% endblocktrans %}"/>{% csrf_token %}
</form>
{% endblock content %}

ident/templates/user/user_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load statictheme from theme %}
{% block heading %}<h1>{% trans "Members &amp; Tools" %}</h1>{% endblock%}

{% block content %}<table class="membership">
<tr><td colspan="2">{% trans "Identist" %} <a href="{% url "membership_by_username" %}"><img src="{% statictheme "images/sortup.png" %}"/></a><a href="{% url "membership_by_-username" %}"><img src="{% statictheme "images/sortdown.png" %}"/></a></td><td>{% trans "Dents" %} <a href="{% url "membership_by_dents" %}"><img src="{% statictheme "images/sortup.png" %}"/></a><a href="{% url "membership_by_-dents" %}"><img src="{% statictheme "images/sortdown.png" %}"/></a></td><td>{% trans "Last active" %} <a href="{% url "membership_page" %}"><img src="{% statictheme "images/sortup.png" %}"/></a><img src="{% statictheme "images/sortdown.png" %}"/></td><td><a href="{% url "membership_by_karma" %}">{% trans "Karma" %}</a></td><td>www</td><td>{% trans "Stalking" %}/<br/>{% trans "Stalked" %}</td></tr>
{% for user in object_list %}{% with profile=user.profile %}
<tr {% if user.profile.dent_count = 0%}class="inactive"{%endif%}><td><img src="{{profile.get_avatar_thumb_url}}" class="ava_thumb"/></td><td><a href="{{user.get_absolute_url}}">{{user}}</a></td><td>{{user.dent_set.count}}</td><td>{{ profile.last_dent_time|date}}</td><td>{{ profile.karma}}</td><td>{%if profile.homepage|slice:":4"|lower == "http" %}<a href="{{profile.homepage}}">www</a>{%endif%}</td><td>{{profile.subscriptions.count}}/{{user.followers.count}} {% if user != request.user %}{% if user in request.user.profile.subscriptions.all %}<a href="{% url "user_unfollow" user.username %}?next={{request.path}}"><img src="{% static "images/unstalk.png" %}" title="{% trans "Unstalk this target" %}"/></a>{%else%}<a href="{% url "user_follow" user.username %}?next={{request.path}}"><img src="{% static "images/stalk.png" %}" title="{% trans "Stalk this target" %}"/></a>{%endif%}{%endif%}</td></tr>{%endwith%}{% endfor %}

{%if is_paginated %}<tr><td colspan="7">{% load paginator %}{% paginator 3 %}</td></tr>{%endif%}
</table>
{% endblock content %}